apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gx0am9oyw-nodejs
  janus-idp.io/tekton: gx0am9oyw-nodejs
  backstage.io/kubernetes-id: gx0am9oyw-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gx0am9oyw-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
